version: '3.7'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - celery
    ports:
      - "5002:5000"
    volumes:
      - .:/code
      - ./celery_init/proj:/code/celery_init/proj
    environment:
      FLASK_ENV: development

  celery:
    build:
      context: ./celery_init
      dockerfile: Dockerfile
    volumes:
      - ./celery_init/proj:/proj
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
