version: '3.7'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - celery
    ports:
      - "5002:5000"
    entrypoint: flask run
    environment:
      FLASK_ENV: development

  celery:
    build:
      context: .
    entrypoint: celery worker -A app.celery --loglevel=info
    depends_on:
      - rabbitmq

  redis:
    image: redis:5.0.5-alpine